
create table events
(
    id    int8 generated by default as identity,
    date  date,
    title varchar(255),
    primary key (id)
);
create table tickets
(
    id       int8 generated by default as identity,
    category int4,
    place    int4,
    event_id int8,
    user_id  int8,
    primary key (id)
);
create table users
(
    id        int8 generated by default as identity,
    email     varchar(255),
    is_active boolean,
    password  varchar(255),
    roles     varchar(255),
    username  varchar(255),
    primary key (id)
);
alter table if exists tickets add constraint FK3utafe14rupaypjocldjaj4ol foreign key (event_id) references events;

alter table if exists tickets add constraint FK4eqsebpimnjen0q46ja6fl2hl foreign key (user_id) references users;